target: yt_tools.dataloader.IterableDataloader
params:
  name: imagenet
  dataset:
    target: yt_tools.yt_iterable_dataset.IterableYTDataset
    params:
      table: //home/yr/ILSVRC/train
      yt_proxy: hahn
      buf_size: 64
  preprocess:
    - in_map:
        image_bytes: image
      target: yt_tools.processing.process_fns.imagenet_preprocessing
      params:
        img_size: 256
        model_type: rae
      out_map: image
    - in_map:
        data: label
      target: yt_tools.processing.process_fns.identity
      out_map: label
  stackable:
    - image
  non_stackable:
    - label